### ISSUE TITLE
Docker compose  - add local mongodb service

### ISSUE THREAD

**Issue by achiyahb** [achiyahb/ai-trainer-bff#3]
Docker compose file working now, and you can use it run the backend and the mysql service
But I had an issue to run with it mongodb service

**Comment by baruchiro** [comment]
Why do you need to add a MongoDB? Which service is using it? What are its requirements?

I mean, if I adding it to the docker-compose, how do I know it is working with the ai-trainer?

**Comment by achiyahb** [comment]
Hi @baruchiro,
Thanks for your comment. As we talked offline, I'm considering refactoring this part and moving away from Mongo. I'm starting to think MySQL might be a better fit here. So for now, I'll close this issue.
